export const GAME_DIFFICULTY = {
  EASY: 'EASY',
  NORMAL: 'NORMAL',
  HARD: 'HARD',
  CUSTOM: 'CUSTOM',
};

export const GAME_STATUS = {
  PLAYING: 'PLAYING',
  WIN: 'WIN',
  LOSE: 'LOSE',
  STOPPED: 'STOPPED',
};

export const DEFAULT_ROWS = 5;
export const DEFAULT_COLS = 10;
export const DEFAULT_MINES = 2;

export const GAME_ACTIONS = {
  UNCOVER_CELL: 'UNCOVER_CELL',
  FLAG_CELL: 'FLAG_CELL',
  START_GAME: 'START_GAME',
  RESET_GAME: 'RESET_GAME',
  SET_DIFFICULTY: 'SET_DIFFICULTY',
  CUSTOM_DIFFICULTY: 'CUSTOM_DIFFICULTY',
};

export const MINES_STYLES = {
  ORIGINAL: 'ORIGINAL',
  HEART: 'HEART',
  DIAMOND: 'DIAMOND',
  STAR: 'STAR',
};
